# The new prompt
format = """
[â”Œâ”€â”€â”€â”€â”€ $username â”€â”€â”€â”€â”€ ](bold #F8AACE)$directory$git_branch$python$cmd_duration
[â”‚](bold #F8AACE) $battery$time
[â”‚](bold #F8AACE)
[â””â”€](bold #F8AACE)$character"""


# Break the new line at the start of the prompt
[line_break]
disabled = false


# The symbol of a succesful command and an error command 
[character]
success_symbol = "[ï‹ ](bold #F8AACE)"
error_symbol = "[ï‹“ ](#DB425B) "

# Truncate the path of the directory to only the basename
[directory]
style = " bold #71D7F5"
truncation_length = 1

# Show the username and divide the directory with a pipe symbol
[username]
style_user = "bold #F8AACE"
show_always = true
style_root = "bold #E37534"
#format = "[$user|]($style) - "
format = "[$user]($style)"

# Show command duration above 500 ms
[cmd_duration]
min_time = 500
style = "bold #98DEDE"
format = "[     ï‰” - $duration]($style)"
show_milliseconds = true

# Show the time in the command prompt
[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = false

# Everything to do with the display of battery
[battery]
format = "[$symbol]($style)$percentage  |  "

# Order of threshold here matters! from low to high
[[battery.display]]
threshold = 20
discharging_symbol = " ï•¼ CHARGE YOUR LAPTOP"
charging_symbol = " ï–‡ "
style = "#FA1400"

[[battery.display]]
threshold = 40
discharging_symbol = " ï•¼ "
charging_symbol = " ï–‡ "
style = "#FAAF28"

[[battery.display]]
threshold = 60
discharging_symbol = " ï•¾ "
charging_symbol = " ï–ˆ "
style = "#F8D50C"

[[battery.display]]
threshold = 85
discharging_symbol = " ï•¿ "
charging_symbol = " ï–‰ "
style = "#88FA78"

[[battery.display]]
threshold = 100
charging_symbol = " ï–„ "
discharging_symbol = " ï•¸ "
style = "#00FA19"

# Shows memory when threshold of 60% is in use
[memory_usage]
disabled = false
threshold = 60
format = "- $symbol[${ram}]($style) "

# Configures the python prompt
[python]
symbol = "ï Ÿ "
format = '[- ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

# Configures the github prompt
[git_branch]
symbol = "ï‚› "
style = "#A779FF"
format = "[| $symbol$branch]($style) "

[git_status]
disabled = true


